package co.gov.sic.expedienteelectronico.businessobject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Usuario implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> aprobadores;
	private java.util.List<java.lang.String> revisores;

	public Usuario() {
	}

	public java.util.List<java.lang.String> getAprobadores() {
		return this.aprobadores;
	}

	public void setAprobadores(java.util.List<java.lang.String> aprobadores) {
		this.aprobadores = aprobadores;
	}

	public java.util.List<java.lang.String> getRevisores() {
		return this.revisores;
	}

	public void setRevisores(java.util.List<java.lang.String> revisores) {
		this.revisores = revisores;
	}

	public Usuario(java.util.List<java.lang.String> aprobadores,
			java.util.List<java.lang.String> revisores) {
		this.aprobadores = aprobadores;
		this.revisores = revisores;
	}

}