package co.gov.sic.expedienteelectronico.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Documento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DOCUMENTO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "DOCUMENTO_ID_SEQ", name = "DOCUMENTO_ID_GENERATOR")
	private java.lang.Integer cod;

	private java.lang.String nombre;

	private java.lang.String usuarioCreador;

	private java.lang.String estado;

	private java.lang.String version;

	private java.lang.Integer idECM;

	private java.lang.Integer folios;

	private java.util.Date fechaCreacion;

	private java.lang.String numeroActo;

	private java.lang.Integer codEvento;

	private java.lang.Integer codTramite;

	private java.lang.Integer codActuacion;

	private java.lang.Integer codSolicitante;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.TipoDocumento codTipoDocumento;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.UnidadDocumental codUnidadDocumental;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.Documento codPadre;

	public Documento() {
	}

	public java.lang.Integer getCod() {
		return this.cod;
	}

	public void setCod(java.lang.Integer cod) {
		this.cod = cod;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getUsuarioCreador() {
		return this.usuarioCreador;
	}

	public void setUsuarioCreador(java.lang.String usuarioCreador) {
		this.usuarioCreador = usuarioCreador;
	}

	public java.lang.String getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.String estado) {
		this.estado = estado;
	}

	public java.lang.String getVersion() {
		return this.version;
	}

	public void setVersion(java.lang.String version) {
		this.version = version;
	}

	public java.lang.Integer getIdECM() {
		return this.idECM;
	}

	public void setIdECM(java.lang.Integer idECM) {
		this.idECM = idECM;
	}

	public java.lang.Integer getFolios() {
		return this.folios;
	}

	public void setFolios(java.lang.Integer folios) {
		this.folios = folios;
	}

	public java.util.Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(java.util.Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public java.lang.String getNumeroActo() {
		return this.numeroActo;
	}

	public void setNumeroActo(java.lang.String numeroActo) {
		this.numeroActo = numeroActo;
	}

	public java.lang.Integer getCodEvento() {
		return this.codEvento;
	}

	public void setCodEvento(java.lang.Integer codEvento) {
		this.codEvento = codEvento;
	}

	public java.lang.Integer getCodTramite() {
		return this.codTramite;
	}

	public void setCodTramite(java.lang.Integer codTramite) {
		this.codTramite = codTramite;
	}

	public java.lang.Integer getCodActuacion() {
		return this.codActuacion;
	}

	public void setCodActuacion(java.lang.Integer codActuacion) {
		this.codActuacion = codActuacion;
	}

	public java.lang.Integer getCodSolicitante() {
		return this.codSolicitante;
	}

	public void setCodSolicitante(java.lang.Integer codSolicitante) {
		this.codSolicitante = codSolicitante;
	}

	public co.gov.sic.expedienteelectronico.entity.TipoDocumento getCodTipoDocumento() {
		return this.codTipoDocumento;
	}

	public void setCodTipoDocumento(
			co.gov.sic.expedienteelectronico.entity.TipoDocumento codTipoDocumento) {
		this.codTipoDocumento = codTipoDocumento;
	}

	public co.gov.sic.expedienteelectronico.entity.UnidadDocumental getCodUnidadDocumental() {
		return this.codUnidadDocumental;
	}

	public void setCodUnidadDocumental(
			co.gov.sic.expedienteelectronico.entity.UnidadDocumental codUnidadDocumental) {
		this.codUnidadDocumental = codUnidadDocumental;
	}

	public co.gov.sic.expedienteelectronico.entity.Documento getCodPadre() {
		return this.codPadre;
	}

	public void setCodPadre(
			co.gov.sic.expedienteelectronico.entity.Documento codPadre) {
		this.codPadre = codPadre;
	}

	public Documento(
			java.lang.Integer cod,
			java.lang.String nombre,
			java.lang.String usuarioCreador,
			java.lang.String estado,
			java.lang.String version,
			java.lang.Integer idECM,
			java.lang.Integer folios,
			java.util.Date fechaCreacion,
			java.lang.String numeroActo,
			java.lang.Integer codEvento,
			java.lang.Integer codTramite,
			java.lang.Integer codActuacion,
			java.lang.Integer codSolicitante,
			co.gov.sic.expedienteelectronico.entity.TipoDocumento codTipoDocumento,
			co.gov.sic.expedienteelectronico.entity.UnidadDocumental codUnidadDocumental,
			co.gov.sic.expedienteelectronico.entity.Documento codPadre) {
		this.cod = cod;
		this.nombre = nombre;
		this.usuarioCreador = usuarioCreador;
		this.estado = estado;
		this.version = version;
		this.idECM = idECM;
		this.folios = folios;
		this.fechaCreacion = fechaCreacion;
		this.numeroActo = numeroActo;
		this.codEvento = codEvento;
		this.codTramite = codTramite;
		this.codActuacion = codActuacion;
		this.codSolicitante = codSolicitante;
		this.codTipoDocumento = codTipoDocumento;
		this.codUnidadDocumental = codUnidadDocumental;
		this.codPadre = codPadre;
	}

}