package co.gov.sic.expedienteelectronico.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class EtapaDocumento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ETAPADOCUMENTO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "ETAPADOCUMENTO_ID_SEQ", name = "ETAPADOCUMENTO_ID_GENERATOR")
	private Integer id;

	private java.lang.String etapa;

	private java.lang.Integer codUsuario;

	private java.lang.String accion;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.HistorialObservaciones codObservacion;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.Documento codDocumento;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.Funcionario funcionario;

	public EtapaDocumento() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getEtapa() {
		return this.etapa;
	}

	public void setEtapa(java.lang.String etapa) {
		this.etapa = etapa;
	}

	public java.lang.Integer getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(java.lang.Integer codUsuario) {
		this.codUsuario = codUsuario;
	}

	public java.lang.String getAccion() {
		return this.accion;
	}

	public void setAccion(java.lang.String accion) {
		this.accion = accion;
	}

	public co.gov.sic.expedienteelectronico.entity.HistorialObservaciones getCodObservacion() {
		return this.codObservacion;
	}

	public void setCodObservacion(
			co.gov.sic.expedienteelectronico.entity.HistorialObservaciones codObservacion) {
		this.codObservacion = codObservacion;
	}

	public co.gov.sic.expedienteelectronico.entity.Documento getCodDocumento() {
		return this.codDocumento;
	}

	public void setCodDocumento(
			co.gov.sic.expedienteelectronico.entity.Documento codDocumento) {
		this.codDocumento = codDocumento;
	}

	public co.gov.sic.expedienteelectronico.entity.Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(
			co.gov.sic.expedienteelectronico.entity.Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	public EtapaDocumento(
			java.lang.Integer id,
			java.lang.String etapa,
			java.lang.Integer codUsuario,
			java.lang.String accion,
			co.gov.sic.expedienteelectronico.entity.HistorialObservaciones codObservacion,
			co.gov.sic.expedienteelectronico.entity.Documento codDocumento,
			co.gov.sic.expedienteelectronico.entity.Funcionario funcionario) {
		this.id = id;
		this.etapa = etapa;
		this.codUsuario = codUsuario;
		this.accion = accion;
		this.codObservacion = codObservacion;
		this.codDocumento = codDocumento;
		this.funcionario = funcionario;
	}

}