package co.gov.sic.expedienteelectronico.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Expediente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "EXPEDIENTE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "EXPEDIENTE_ID_SEQ", name = "EXPEDIENTE_ID_GENERATOR")
	private Integer id;

	private java.util.Date anio;

	private java.lang.String control;

	private java.lang.String numeroRadicado;

	@org.kie.api.definition.type.Label(value = "Usuario Proyector")
	private java.lang.String usuarioProyector;

	public Expediente() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.util.Date getAnio() {
		return this.anio;
	}

	public void setAnio(java.util.Date anio) {
		this.anio = anio;
	}

	public java.lang.String getControl() {
		return this.control;
	}

	public void setControl(java.lang.String control) {
		this.control = control;
	}

	public java.lang.String getNumeroRadicado() {
		return this.numeroRadicado;
	}

	public void setNumeroRadicado(java.lang.String numeroRadicado) {
		this.numeroRadicado = numeroRadicado;
	}

	public java.lang.String getUsuarioProyector() {
		return this.usuarioProyector;
	}

	public void setUsuarioProyector(java.lang.String usuarioProyector) {
		this.usuarioProyector = usuarioProyector;
	}

	public Expediente(java.lang.Integer id, java.util.Date anio,
			java.lang.String control, java.lang.String numeroRadicado,
			java.lang.String usuarioProyector) {
		this.id = id;
		this.anio = anio;
		this.control = control;
		this.numeroRadicado = numeroRadicado;
		this.usuarioProyector = usuarioProyector;
	}

}