package co.gov.sic.expedienteelectronico.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Funcionario implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "FUNCIONARIO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "FUNCIONARIO_ID_SEQ", name = "FUNCIONARIO_ID_GENERATOR")
	private Integer id;

	private java.lang.String nombre;

	private java.lang.String apellido;

	private java.lang.String numDocumento;

	private java.lang.Integer codCargo;

	private java.lang.String grado;

	private java.lang.String estado;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.TipoDocIdentidad codTipoDoc;

	public Funcionario() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getApellido() {
		return this.apellido;
	}

	public void setApellido(java.lang.String apellido) {
		this.apellido = apellido;
	}

	public java.lang.String getNumDocumento() {
		return this.numDocumento;
	}

	public void setNumDocumento(java.lang.String numDocumento) {
		this.numDocumento = numDocumento;
	}

	public java.lang.Integer getCodCargo() {
		return this.codCargo;
	}

	public void setCodCargo(java.lang.Integer codCargo) {
		this.codCargo = codCargo;
	}

	public java.lang.String getGrado() {
		return this.grado;
	}

	public void setGrado(java.lang.String grado) {
		this.grado = grado;
	}

	public java.lang.String getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.String estado) {
		this.estado = estado;
	}

	public co.gov.sic.expedienteelectronico.entity.TipoDocIdentidad getCodTipoDoc() {
		return this.codTipoDoc;
	}

	public void setCodTipoDoc(
			co.gov.sic.expedienteelectronico.entity.TipoDocIdentidad codTipoDoc) {
		this.codTipoDoc = codTipoDoc;
	}

	public Funcionario(java.lang.Integer id, java.lang.String nombre,
			java.lang.String apellido, java.lang.String numDocumento,
			java.lang.Integer codCargo, java.lang.String grado,
			java.lang.String estado,
			co.gov.sic.expedienteelectronico.entity.TipoDocIdentidad codTipoDoc) {
		this.id = id;
		this.nombre = nombre;
		this.apellido = apellido;
		this.numDocumento = numDocumento;
		this.codCargo = codCargo;
		this.grado = grado;
		this.estado = estado;
		this.codTipoDoc = codTipoDoc;
	}

}