package co.gov.sic.expedienteelectronico.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class HistorialObservaciones implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "HISTORIALOBSERVACIONES_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "HISTORIALOBSERVACIONES_ID_SEQ", name = "HISTORIALOBSERVACIONES_ID_GENERATOR")
	private Integer id;

	private java.lang.String version;

	private java.lang.String descObservacion;

	private java.util.Date fecRegistro;

	private java.lang.Integer idUsuarioCreador;

	private java.lang.String etapa;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.Funcionario funcionario;

	public HistorialObservaciones() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getVersion() {
		return this.version;
	}

	public void setVersion(java.lang.String version) {
		this.version = version;
	}

	public java.lang.String getDescObservacion() {
		return this.descObservacion;
	}

	public void setDescObservacion(java.lang.String descObservacion) {
		this.descObservacion = descObservacion;
	}

	public java.util.Date getFecRegistro() {
		return this.fecRegistro;
	}

	public void setFecRegistro(java.util.Date fecRegistro) {
		this.fecRegistro = fecRegistro;
	}

	public java.lang.Integer getIdUsuarioCreador() {
		return this.idUsuarioCreador;
	}

	public void setIdUsuarioCreador(java.lang.Integer idUsuarioCreador) {
		this.idUsuarioCreador = idUsuarioCreador;
	}

	public java.lang.String getEtapa() {
		return this.etapa;
	}

	public void setEtapa(java.lang.String etapa) {
		this.etapa = etapa;
	}

	public co.gov.sic.expedienteelectronico.entity.Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(
			co.gov.sic.expedienteelectronico.entity.Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	public HistorialObservaciones(java.lang.Integer id,
			java.lang.String version, java.lang.String descObservacion,
			java.util.Date fecRegistro, java.lang.Integer idUsuarioCreador,
			java.lang.String etapa,
			co.gov.sic.expedienteelectronico.entity.Funcionario funcionario) {
		this.id = id;
		this.version = version;
		this.descObservacion = descObservacion;
		this.fecRegistro = fecRegistro;
		this.idUsuarioCreador = idUsuarioCreador;
		this.etapa = etapa;
		this.funcionario = funcionario;
	}

}