package co.gov.sic.expedienteelectronico.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PERSONA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PERSONA_ID_SEQ", name = "PERSONA_ID_GENERATOR")
	private Integer id;

	private java.lang.String nombre;

	private java.lang.String apellido;

	private java.lang.String numDocumento;

	private java.lang.String direccion;

	private java.lang.String telefono;

	private java.lang.String celular;

	private java.lang.String correo;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.TipoDocIdentidad codDocIdentidad;

	public Persona() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getApellido() {
		return this.apellido;
	}

	public void setApellido(java.lang.String apellido) {
		this.apellido = apellido;
	}

	public java.lang.String getNumDocumento() {
		return this.numDocumento;
	}

	public void setNumDocumento(java.lang.String numDocumento) {
		this.numDocumento = numDocumento;
	}

	public java.lang.String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(java.lang.String direccion) {
		this.direccion = direccion;
	}

	public java.lang.String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(java.lang.String telefono) {
		this.telefono = telefono;
	}

	public java.lang.String getCelular() {
		return this.celular;
	}

	public void setCelular(java.lang.String celular) {
		this.celular = celular;
	}

	public java.lang.String getCorreo() {
		return this.correo;
	}

	public void setCorreo(java.lang.String correo) {
		this.correo = correo;
	}

	public co.gov.sic.expedienteelectronico.entity.TipoDocIdentidad getCodDocIdentidad() {
		return this.codDocIdentidad;
	}

	public void setCodDocIdentidad(
			co.gov.sic.expedienteelectronico.entity.TipoDocIdentidad codDocIdentidad) {
		this.codDocIdentidad = codDocIdentidad;
	}

	public Persona(
			java.lang.Integer id,
			java.lang.String nombre,
			java.lang.String apellido,
			java.lang.String numDocumento,
			java.lang.String direccion,
			java.lang.String telefono,
			java.lang.String celular,
			java.lang.String correo,
			co.gov.sic.expedienteelectronico.entity.TipoDocIdentidad codDocIdentidad) {
		this.id = id;
		this.nombre = nombre;
		this.apellido = apellido;
		this.numDocumento = numDocumento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.celular = celular;
		this.correo = correo;
		this.codDocIdentidad = codDocIdentidad;
	}

}