package co.gov.sic.expedienteelectronico.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class TipoDocIdentidad implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TIPODOCIDENTIDAD_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "TIPODOCIDENTIDAD_ID_SEQ", name = "TIPODOCIDENTIDAD_ID_GENERATOR")
	private Integer id;

	private java.lang.String codTipoDoc;

	private java.lang.String descTipoDoc;

	public TipoDocIdentidad() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getCodTipoDoc() {
		return this.codTipoDoc;
	}

	public void setCodTipoDoc(java.lang.String codTipoDoc) {
		this.codTipoDoc = codTipoDoc;
	}

	public java.lang.String getDescTipoDoc() {
		return this.descTipoDoc;
	}

	public void setDescTipoDoc(java.lang.String descTipoDoc) {
		this.descTipoDoc = descTipoDoc;
	}

	public TipoDocIdentidad(java.lang.Integer id, java.lang.String codTipoDoc,
			java.lang.String descTipoDoc) {
		this.id = id;
		this.codTipoDoc = codTipoDoc;
		this.descTipoDoc = descTipoDoc;
	}

}