package co.gov.sic.expedienteelectronico.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class UnidadDocumental implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "UNIDADDOCUMENTAL_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "UNIDADDOCUMENTAL_ID_SEQ", name = "UNIDADDOCUMENTAL_ID_GENERATOR")
	private Integer id;

	private java.lang.Integer codDependiencia;

	private java.lang.Integer codUnidadDocumental;

	private java.lang.String nombre;

	private java.util.Date fechaCreacion;

	private java.lang.String versionTRD;

	private java.lang.Integer descriptor1;

	private java.lang.Integer descriptor2;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.Expediente codExpediente;

	private java.lang.String codSerie;

	private java.lang.String codSubSerie;

	private java.lang.String codTpgDoc;

	public UnidadDocumental() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getCodDependiencia() {
		return this.codDependiencia;
	}

	public void setCodDependiencia(java.lang.Integer codDependiencia) {
		this.codDependiencia = codDependiencia;
	}

	public java.lang.Integer getCodUnidadDocumental() {
		return this.codUnidadDocumental;
	}

	public void setCodUnidadDocumental(java.lang.Integer codUnidadDocumental) {
		this.codUnidadDocumental = codUnidadDocumental;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.util.Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(java.util.Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public java.lang.String getVersionTRD() {
		return this.versionTRD;
	}

	public void setVersionTRD(java.lang.String versionTRD) {
		this.versionTRD = versionTRD;
	}

	public java.lang.Integer getDescriptor1() {
		return this.descriptor1;
	}

	public void setDescriptor1(java.lang.Integer descriptor1) {
		this.descriptor1 = descriptor1;
	}

	public java.lang.Integer getDescriptor2() {
		return this.descriptor2;
	}

	public void setDescriptor2(java.lang.Integer descriptor2) {
		this.descriptor2 = descriptor2;
	}

	public co.gov.sic.expedienteelectronico.entity.Expediente getCodExpediente() {
		return this.codExpediente;
	}

	public void setCodExpediente(
			co.gov.sic.expedienteelectronico.entity.Expediente codExpediente) {
		this.codExpediente = codExpediente;
	}

	public java.lang.String getCodSerie() {
		return this.codSerie;
	}

	public void setCodSerie(
			java.lang.String codSerie) {
		this.codSerie = codSerie;
	}

	public java.lang.String getCodSubSerie() {
		return this.codSubSerie;
	}

	public void setCodSubSerie(
			java.lang.String codSubSerie) {
		this.codSubSerie = codSubSerie;
	}

	public java.lang.String getCodTpgDoc() {
		return this.codTpgDoc;
	}

	public void setCodTpgDoc(
			java.lang.String codTpgDoc) {
		this.codTpgDoc = codTpgDoc;
	}

	public UnidadDocumental(java.lang.Integer id,
			java.lang.Integer codDependiencia,
			java.lang.Integer codUnidadDocumental, java.lang.String nombre,
			java.util.Date fechaCreacion, java.lang.String versionTRD,
			java.lang.Integer descriptor1, java.lang.Integer descriptor2,
			co.gov.sic.expedienteelectronico.entity.Expediente codExpediente,
			java.lang.String codSerie,
			java.lang.String codSubSerie,
			java.lang.String codTpgDoc) {
		this.id = id;
		this.codDependiencia = codDependiencia;
		this.codUnidadDocumental = codUnidadDocumental;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.versionTRD = versionTRD;
		this.descriptor1 = descriptor1;
		this.descriptor2 = descriptor2;
		this.codExpediente = codExpediente;
		this.codSerie = codSerie;
		this.codSubSerie = codSubSerie;
		this.codTpgDoc = codTpgDoc;
	}

}