package co.gov.sic.expedienteelectronico.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class UsuarioDocumento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "USUARIODOCUMENTO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@javax.persistence.SequenceGenerator(sequenceName = "USUARIODOCUMENTO_ID_SEQ", name = "USUARIODOCUMENTO_ID_GENERATOR")
	private co.gov.sic.expedienteelectronico.entity.Rol codRol;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.Documento codDocumento;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private co.gov.sic.expedienteelectronico.entity.Funcionario codFuncionario;

	private java.lang.Integer idFuncionario;

	public UsuarioDocumento() {
	}

	public co.gov.sic.expedienteelectronico.entity.Rol getCodRol() {
		return this.codRol;
	}

	public void setCodRol(co.gov.sic.expedienteelectronico.entity.Rol codRol) {
		this.codRol = codRol;
	}

	public co.gov.sic.expedienteelectronico.entity.Documento getCodDocumento() {
		return this.codDocumento;
	}

	public void setCodDocumento(
			co.gov.sic.expedienteelectronico.entity.Documento codDocumento) {
		this.codDocumento = codDocumento;
	}

	public co.gov.sic.expedienteelectronico.entity.Funcionario getCodFuncionario() {
		return this.codFuncionario;
	}

	public void setCodFuncionario(
			co.gov.sic.expedienteelectronico.entity.Funcionario codFuncionario) {
		this.codFuncionario = codFuncionario;
	}

	public java.lang.Integer getIdFuncionario() {
		return this.idFuncionario;
	}

	public void setIdFuncionario(java.lang.Integer idFuncionario) {
		this.idFuncionario = idFuncionario;
	}

	public UsuarioDocumento(co.gov.sic.expedienteelectronico.entity.Rol codRol,
			co.gov.sic.expedienteelectronico.entity.Documento codDocumento,
			co.gov.sic.expedienteelectronico.entity.Funcionario codFuncionario,
			java.lang.Integer idFuncionario) {
		this.codRol = codRol;
		this.codDocumento = codDocumento;
		this.codFuncionario = codFuncionario;
		this.idFuncionario = idFuncionario;
	}

}